### ISSUE TITLE
Example won't compile

### ISSUE THREAD

**Issue by mfirry** [analogweb/analogweb-scala#22]
Hi, trying your simple example won't work.

I get 
```
Hello.scala:8: ambiguous reference to overloaded definition,
[error] both method run in object Servers of type (x$1: Int, x$2: String*)Unit
[error] and  method run in object Servers of type (x$1: String*)Unit
[error] match expected type ?
[error]   def main(args: Array[String]) = Servers.run
```

**Comment by y2k2mt** [comment]
Hi, thank you for reporting.
What version do you use? if you use 0.9.13 , please try 0.9.14.

**Comment by mfirry** [comment]
0.9.14. I endend up with this https://github.com/mfirry/web-frameworks-templates/blob/master/analogweb/src/main/scala/com/example/Hello.scala

**Comment by y2k2mt** [comment]
I can be reproduced it.
It needs to put '()' after 'Severs.run' and 'import' statement.
Documentation have been fixed.
Thanks again.

**Comment by mfirry** [comment]
Great! Thanks!
